### ISSUE TITLE
我在EventHandler里使用仓储，会出现报错System.ObjectDisposedException异常

### ISSUE THREAD

**Issue by HoboCY** [EasyAbp/Abp.EventBus.CAP#24]
版本3.3.0
我将CAP包都改到了3.1.2
继承IDistributedEventHandler<>的handler里注入仓储使用会出现异常，具体信息如下
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MySqlConnection'.
   at MySql.Data.MySqlClient.MySqlConnection.VerifyNotDisposed() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 706
   at MySql.Data.MySqlClient.MySqlConnection.get_Session() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 481
   at MySqlConnector.Core.ICancellableCommandExtensions.ResetCommandTimeout(ICancellableCommand command) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ICancellableCommand.cs:line 41
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
   at System.Data.Common.DbCommand.ExecuteReaderAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

**Comment by gdlcf88** [comment]
How to reproduce your problem?

**Comment by HoboCY** [comment]
> 
EasyAbp.Abp.EventBus.CAP 3.3.0 版本下，EventHandler里仓储使用异步即会出现报错

**Comment by HoboCY** [comment]
> How to reproduce your problem?

![image](https://user-images.githubusercontent.com/31683826/195264100-d28c0237-64e9-4d83-b5a9-9c7966db65d4.png)
像这样，一个简单的异步就会报错

**Comment by gdlcf88** [comment]
Can't help. You can try manage UOW yourself.

If you cannot solve it, try to reproduce it in the latest version (and also share the project for us), and create an new issue with English.
